language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
sudo: required
services: docker
install: "pip install -r requirements.txt"
script: bash test/test.sh
after_success:
    - docker login -u="$DOCKER_HUB_USER" -p="$DOCKER_HUB_PASS"
    - docker build -t felipeng/mars:latest .
    - docker push felipeng/mars:latest
